config/routes.rb
MVNHWebSite::Application.routes.draw do

  resources :organisations

  match '/contact', :to => 'pages#contact'
  match '/events', :to => 'pages#events'
  match '/resources', :to => 'pages#resources'
  match '/whatishere', :to => 'pages#whatishere'
  match '/birds', :to => 'pages#birds'
  match '/butterflies', :to => 'pages#butterflies'
  match '/fungi', :to => 'pages#fungi'
  match '/plants', :to => 'pages#plants'
  match '/organisation_list', :to => 'organisation_list#index'

  root :to => 'pages#home'

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/organisation_list_controller.rb
class OrganisationListController < ApplicationController
  def index
    @title = "Organisations"
    @organisations = Organisation.all
  end

end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organisations }
    end
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/new
  # GET /organisations/new.json
  def new
    @organisation = Organisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organisation }
    end
  end

  # GET /organisations/1/edit
  def edit
    @organisation = Organisation.find(params[:id])
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(params[:organisation])

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render json: @organisation, status: :created, location: @organisation }
      else
        format.html { render action: "new" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organisations/1
  # PUT /organisations/1.json
  def update
    @organisation = Organisation.find(params[:id])

    respond_to do |format|
      if @organisation.update_attributes(params[:organisation])
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def resources
    @title = "Resources"
  end

  def events
    @title = "Events"
  end

  def contact
    @title = "Contact Us"
  end

  def whatishere
    @title = "What is Here"
  end

  def birds
    @title = "Birds"
  end

  def butterflies
    @title = "Butterflies"
  end

  def fungi
    @title = "Fungi"
  end

  def plants
    @title = "Plants"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Mole Valley's Natural History"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/organisation_list_helper.rb
module OrganisationListHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <h1>Mole Valley&#8217;s Natural History</h1>
</header>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li> <%= link_to "Home", root_path %> </li>
    <li> <%= link_to "Resources", resources_path %> </li>
    <li> <%= link_to "Organisations", organisation_list_path %> </li>
    <li> <%= link_to "What is here?", whatishere_path %> </li>
    <li> <%= link_to "Events", events_path %> </li>
    <li> <%= link_to "Contact", contact_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <meta name="description" content="">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <section id="main">
      <%= render 'layouts/header' %>
      <%= render 'layouts/navigation' %>

      <%= yield %>

    </section>


</body>
</html>

app/views/organisation_list/index.html.erb
<article>

  <h1>Organisations</h1>

  <p>
    A very wide range of organisations have a natural history remit in Mole Valley.
    This page contains a list of all the main ones that we are aware of.
    Links are provided to their respective web sites where available.
    Otherwise we provide contact details.
  </p>

  <% @organisations.each do |organisation| %>
      <div class="entry">
        <% web_address = organisation.website %>
        <h3><%= link_to_if(web_address, organisation.name, web_address, {:target => "_blank"}) %></h3>

        <p>
          <%= organisation.description %>
        </p>

      </div>
  <% end %>

</article>

app/views/organisations/_form.html.erb
<%= form_for(@organisation) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<h1>Listing organisations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisations.each do |organisation| %>
  <tr>
    <td><%= organisation.name %></td>
    <td><%= link_to 'Show', organisation %></td>
    <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
    <td><%= link_to 'Destroy', organisation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render 'form' %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organisation.name %>
</p>

<p>
  <b>Website:</b>
  <%= @organisation.website %>
</p>

<p>
  <b>Description:</b>
  <%= @organisation.description %>
</p>


<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>

app/views/pages/birds.html.erb
<article>
  <section class="taxon">
    <p>
      Mole Valley is home to a wide range of bird species, many of which favour
      particular habitats. Some of these are highlighted below:
    </p>
  </section>

  <section class="taxon">
    <h2>River Mole</h2>
    <p>
      <%= image_tag "birds/Kingfisher with fish.jpg", :class => 'birds',
                    :title => 'Kingfisher with fish. Copyright: Jeremy Early', :alt => "Kingfisher with fish" %>
      Kingfishers can be seen along the length of the river – a flash of blue and
      orange flying swiftly past. Grey wagtails are also common often seen around
      the Leatherhead Town Bridge and in Winter goosanders can be seen swimming
      along the river.
    </p>
  </section>

  <section class="taxon">
    <h2>Ponds and streams</h2>
    <p>
      <%= image_tag "birds/Grey_Wagtail.jpg", :class => 'birds',
                    :title => 'Grey Wagtail. Copyright: Jeremy Early', :alt => "Grey Wagtail" %>
      Many common birds can be seen on our ponds and streams including mallards,
      coots, moorhens, Canada geese, greylag geese and grey wagtails.
    </p>
  </section>

  <section class="taxon">
    <h2>Farmland</h2>
    <%= image_tag "birds/red legged partridge.jpg", :class => 'birds',
                  :title => 'Red-legged Partridge. Copyright: Heather & Don Gerrard', :alt => "Red-legged Partridge" %>
    <p>
      There is a range of birds found in our farmland habitat including game birds
      such as pheasants and red-legged partridge. In the hedgerows you can see
      yellowhammers and finches and feeding in the fields there are often skylarks
      and thrushes; in the Winter the song and mistle thrushes are joined by
      redwings and fieldfares from Scandinavia.
    </p>
  </section>

  <section class="taxon">
    <h2>Woodland</h2>
    <p>
      <%= image_tag "birds/lesser redpoll.jpg", :class => 'birds',
                    :title => 'Lesser Redpoll. Copyright: Heather & Don Gerrard', :alt => "Lesser Redpoll" %>
      Our woodland areas host a wide variety of birds including 5 species of tit
      (blue, great, coal, long-tailed and marsh), great spotted woodpeckers,
      redpolls and siskins.
    </p>
  </section>

  <section class="taxon">
    <h2>Urban parks, green spaces and gardens</h2>
    <p>
      <%= image_tag "birds/House-Martin.jpg", :class => 'birds',
                    :title => 'House Martin collecting nesting material. Copyright: Jeremy Early', :alt => "House Martin" %>
      Another rich environment for several species of birds which include:
      green woodpeckers, robins, blackbirds, tits, pied wagtails and many more.
    </p>
  </section>

  <section class="taxon">
    <h2>Commons and Heaths</h2>
    <p>
      <%= image_tag "birds/Nightingale.jpg", :class => 'birds',
                    :title => 'Nightingale. Copyright: Jeremy Early', :alt => "Nightingale" %>
      Our commons and heathlands are home all year round to birds such as finches
      and tits. Rarer summer migrants include woodlarks (Headley Heath),
      nightingales and warblers (Bookham Common). Arguably the most important
      bird site in Mole Valley is Bookham Common for nightingales.
    </p>
  </section>
</article>

app/views/pages/butterflies.html.erb
<article>
  <section class="taxon">
    <h1>Butterflies</h1>

    <p>
      <%= image_tag "butterflies/White_Letter_Hairstreak.jpg", :class => 'butterfliesLeft',
                    :title => 'White-letter Hairstreak. Copyright: Jeremy Early', :alt => "White-letter Hairstreak butterfly" %>
      Mole
      Valley is nationally important for its butterflies. These are cold-blooded
      insects that need warmth, shelter and the right plants to be able to fly, feed
      and breed. The warm, south-facing slopes of the North Downs with their variety
      of plants, support the highest numbers of butterflies locally. Most adult
      butterflies need nectar to feed on, and will take it from a wide range of
      flowers. A few feed on ‘honeydew’, a sweet sticky substance produced by aphids,
      which coats the leaves of trees, and the Purple and White-letter Hairstreaks
      which use it spend most of their time in the treetops. Caterpillars are choosy
      about what they will eat, and female butterflies lay eggs on the plants that
      the caterpillar will feed on as soon as it hatches. Adonis Blue and Chalkhill
      Blue caterpillars feed on Horseshoe Vetch, which only grows on chalk grassland,
      so they are restricted to this habitat. Caterpillars of the Red Admiral and
      Peacock feed on nettles, and these butterflies are found in many more places,
      including parks and gardens.
    </p>

    <p>
      Many
      kinds of butterfly have declined in numbers in recent decades, and some need
      conservation work, such as grazing by cattle or sheep, to provide the right
      conditions for them to survive. These conditions are suitable for many other
      insects too, most of which are less conspicuous than butterflies. Thus
      butterflies are good ‘indicator species’; if a site supports a good number of
      butterflies of different kinds, it is likely to have a good range of other
      insects too, which provide food needed by other wildlife, such as birds and
      bats.
    </p>


    <p>
      Here
      we illustrate five butterflies found in Mole Valley that are of conservation
      importance as well as being attractive and interesting. While a visit to a good
      chalk grassland or woodland site is necessary to find these five, many others
      can be seen visiting gardens, parks and roadside verges. Up to 20 different
      kinds of butterfly, including the Brimstone, Peacock, Red Admiral and Speckled
      Wood, can be attracted to gardens to feed by providing a supply of nectar from
      spring through to autumn (Buddleia, Michaelmas Daisy and Aubrieta are among the
      best flowers for this).
    </p>
  </section>

  <section class="taxon">
    <p>
      <%= image_tag "butterflies/Silver_Spotted_Skipper.jpg", :class => 'butterfliesRight',
                    :title => 'Silver-spotted Skipper. Copyright: Jeremy Early', :alt => "Silver-spotted Skipper butterfly" %>
      <strong>Silver-spotted Skipper:</strong> This little butterfly
      flies in August on the downs. Box Hill is a good place to see it. A few decades
      ago it was so rare nationally that it was feared it might become extinct in
      Britain, and the our local chalk grassland held important populations. Its
      caterpillars feed only on a grass called Sheep’s Fescue, and it used to breed
      only on south-facing chalk slopes, in the hottest spots with very short grass
      and lots of bare ground. Lack of grazing and loss of chalk grassland to
      agriculture and housing led to the extinction of many populations. In recent
      years however, conservation grazing has helped the Silver-spotted Skipper to
      survive, warmer summers have enabled it to breed in slightly longer grass, and
      it has recovered in numbers and spread to new sites. It flies close to the
      ground on hot August days, visiting Stemless Thistles for nectar, but if
      disturbed it flies away very fast.
    </p>
  </section>

  <section class="taxon">
    <p>
      <%= image_tag "butterflies/adonis_blue.jpg", :class => 'butterfliesLeft',
                    :title => 'Adonis Blue on Eyebright', :alt => "Adonis Blue butterfly on eyebright" %>
      <strong>The Adonis Blue </strong>is a
      vivid blue butterfly that is a favourite of butterfly enthusiasts. It has two
      generations a year, and can be seen in May and again in August. Denbies
      Hillside, to the west of Dorking is the best place to see it in Mole Valley.
      Like the Silver-spotted Skipper it is a chalk grassland butterfly that became
      very rare in the 1970s and ‘80s, due to loss of the habitat it needs. Because
      Horseshoe Vetch, which the caterpillars feed on, is itself a scarce plant that
      has disappeared from many places on the downs and does not easily re-colonise,
      it has not recovered its lost populations here, though it has done better in
      Wiltshire and Dorset. Grazing is carried out on the few sites in Surrey where
      it survives, and must be carefully monitored to provide the right conditions.
      The caterpillar produces a sweet liquid which attracts ants that form an
      excited cluster around it. This helps to protect it from predators and parasites,
      and both the caterpillar and the ant benefit from the association.

    </p>
  </section>

  <section class="taxon">
    <p>
      <%= image_tag "butterflies/Brown_Hairstreak.jpg", :class => 'butterfliesRight',
                    :title => 'Brown Hairstreak. Copyright: Jeremy Early', :alt => "Brown hairstreak butterfly" %>
      <strong>Brown Hairstreak: </strong>This
      is the last British butterfly to emerge in the summer, not flying until August
      and September. It is nationally scarce, with scattered populations in a few
      counties. The weald of Surrey and Sussex is one of its strongholds, and in the
      last 20 years it has extended its range, and now occurs across Mole Valley and
      up to the southern edge of London. Males stay up in the treetops, but females
      fly out from these to lay their eggs singly on young shoots of Blackthorn in
      hedges, woodland rides and even gardens. The adults are rarely seen, which is a
      shame because this is a beautiful butterfly. The eggs stay on the Blackthorn
      all winter till they hatch in April, and volunteers map the distribution of the
      butterfly by searching for them. It gives enthusiasts a chance to spot
      butterflies even in the coldest months!
    </p>
  </section>

  <section class="taxon">
    <p>
      <%= image_tag "butterflies/Purple-Emperor.jpg", :class => 'butterfliesLeft',
                    :title => 'Purple Emperor. Copyright: Jeremy Early', :alt => "Purple Emperor butterfly" %>
      <strong>Purple Emperor: </strong>
      People
      come from all over Britain to Mole Valley to see this spectacular butterfly!
      Bookham Common is one of the top places in the country for visitors to get good
      views, and many join special guided walks run by the National Trust and by
      Butterfly Conservation. The Purple Emperor has a limited distribution,
      occurring in woodland in a few southern counties of England. It flies from the
      end of June till the beginning of August. Only the males have the stunning
      purple sheen on the wings, but the females are still striking butterflies. This
      butterfly never visits flowers, but males may land on woodland rides and can be
      approached – with care – to obtain good views. Eggs are laid on Sallow bushes
      and the caterpillars feed on the leaves in late summer and the following
      spring, spending the winter camouflaged on the stems.
    </p>
  </section>

  <section class="taxon">
    <p>
      <%= image_tag "butterflies/Silver_Washed_Fritillary.jpg", :class => 'butterfliesRight',
                    :title => 'Silver-washed Fritillary. Copyright: Jeremy Early', :alt => "Silver-washed Fritillary butterfly" %>
      <strong>Silver-washed Fritillary: </strong>This is another large, spectacular woodland
      butterfly. It occurs in several woods in Mole Valley and can be seen from late
      June till mid-August in sunny rides and clearings, where it feeds on flowers,
      especially bramble. Unusually, the eggs are not laid on the plants that the
      caterpillars eat, but on mossy tree-trunks close to patches of Common
      Dog-violet. The eggs hatch after a few weeks but the caterpillars stay on the
      tree-trunk until spring, when they drop or crawl down to the ground to feed on
      the violet leaves, basking in the sun on dead leaves to raise their
      temperature. At Box Hill this butterfly occurs along with the very similar
      <strong>Dark Green Fritillary</strong>, which is very
      scarce in Surrey and Box Hill is now the only place where it is regularly seen.
      It also needs violets for its caterpillars to feed on, but unlike the
      Silver-washed, this Fritillary is a grassland butterfly, feeding on Hairy
      Violet in longer grass and around the edge of patches of scrub.
    </p>
  </section>
</article>

app/views/pages/contact.html.erb
<article>
  <h1>Contact Us</h1>
  <%= image_tag "Denbies-Hillside.jpg", :class => "birdsCentre", :title => 'Denbies Hillside. Copyright: Jeremy Early', :alt => "Denbies Hillside near Dorking" %>
  <p>
    We are always looking for additional support. A contact point is currently being arranged (February 2012)
    and will be added as soon as possible. Do get in touch if you would either like to offer help or
    if you would like some advice on nature conservation in Mole Valley.
  </p>
  <p>
    N.B. This page is currently being revised and an updated version will be provided shortly.
  </p>
</article>

app/views/pages/home.html.erb
<article>
  <h1>Mole Valley&#8217;s Natural History</h1>


  <p>

    Welcome to Mole Valley&#8217;s Natural History. Mole Valley has stunning landscapes with a natural history that is
    internationally
    and nationally important. We hope this site will help you appreciate the value of the district&#8217;s natural
    phenomena, and
    encourage greater care and appreciation of this very special place. The natural beauty of Mole Valley&#8217;s
    landscape has
    influenced and inspired many artists, writers and poets including John Keats and Jane Austen.
  </p>
  <%= image_tag "broadwoods_folley.jpg", :class => 'main-image', :alt => "Broadwood's Folley" %>
  <p>
    The rich landscape of Mole Valley is comprised of four distinct landscape types or character areas formed by the
    underlying
    geology;
    <a href="http://www.naturalengland.org.uk/ourwork/farming/funding/ecs/sitings/areas/114.aspx" target="_blank">Thames Basin
      Lowlands</a>,
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/north_downs.aspx" target="_blank">North Downs</a>,
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/wealden_greensand.aspx" target="_blank">Wealden
      Greensand</a> and the
    <a href="http://www.naturalengland.org.uk/ourwork/landscape/englands/character/areas/low_weald.aspx" target="_blank">Low
      Weald</a>.
    Perhaps most dominant and significant is the
    chalk escarpment of the North Downs, home to
    <a href="http://www.nationaltrust.org.uk/box-hill/" target="_blank">Boxhill</a>,
    which crosses the District and can be viewed from as far away as the
    South Downs. The North Downs are paralleled to the South by an undulating and heavily wooded greensand ridge rising
    to
    <a href="http://www.nationaltrust.org.uk/home/item258348/" target="_blank">Leith Hill</a>
    in the west of the District. South of this is the gently undulating Weald which is more extensively wooded in the
    South
    West of the District. To the North of the District, the Thames Lowland Basin acts as the interface between the
    countryside and
    urban edge and is largely broad and flat with strong field patterns and wooded shaws.
  </p>

  <p>
    The District&#8217;s name sake, the
    <a href="http://en.wikipedia.org/wiki/River_Mole" target="_blank">River Mole</a>,
    carves its path, starting near Gatwick as a collection of small tributaries in the
    Weald before carving through the steep sided valley of the North Downs, creating the Mole Gap, before extending
    beyond
    Leatherhead and Fetcham to meet the Thames to the North.
  </p>

  <p>
    Such is the importance of the District it is covered by an array of landscape designations including a European
    designation of
    an
    <acronym title="Special Area of Conservation"><a href="http://www.jncc.gov.uk/protectedsites/sacselection/sac.asp?EUcode=UK0012804" target="_blank">SAC</a></acronym>,
    <acronym title="Site of Special Scientific Interest"><a href="http://www.sssi.naturalengland.org.uk/Special/sssi/searchresults.cfm?sssi_name=&amp;frmcounty=1039" target="_blank">SSSI&#8217;s</a></acronym>,
    <acronym title="Sites of Nature Conservation Importance">SNCI&#8217;s</acronym>,
    <acronym title="National Nature Reserve"><a href="http://www.cityoflondon.gov.uk/Corporation/LGNL_Services/Environment_and_planning/Parks_and_open_spaces/Ashtead_Common" target="_blank">NNR</a></acronym>,
    <acronym title="Local Nature Reserve"><a href="http://www.molevalley.gov.uk/index.cfm?articleid=5088" target="_blank">LNR&#8217;s</a></acronym>
    and an
    <acronym title="Special Protection Area"><a href="http://www.surreywildlifetrust.org.uk/Default.asp?mainmenu=ourplaces&amp;SiteID=%7bD78D43CA-91DF-4C6C-A031-0C97ED85B642%7d&amp;EntityID=%7bD78D43CA-91DF-4C6C-A031-0C97ED85B642%7d" target="_blank">SPA</a></acronym>.
  </p>

  <p>
    The district is one of most wooded parts of Surrey and England with 30.5% woodland cover compared against a national
    average of
    7.5 %. This, in part, is made up of nearly 4000Ha of Broadleaf Woodland, some of which is ancient, and, just over
    2000Ha of
    mixed woodland.
  </p>

  <p>
    The presence of a rich and varied underlying
    <a href="http://www.landis.org.uk/soilscapes" target="_blank">geology</a>
    means the Mole Valley district is home to a rich array of
    <%= link_to "species", whatishere_path %> and
    <a href="http://www.surreycc.gov.uk/sccwebsite/sccwspages.nsf/LookupWebPagesByTITLE_RTF/Surrey+Biodiversity+Action+Plan?opendocument" target="_blank">habitats</a>
    including chalk grassland, lowland heath, wood pasture, and dry acid grassland to name a few, as well as the UK’s
    only
    native <%= link_to "Boxwood", plants_path %>
    population and strong populations of the
    <%= link_to "Purple Emperor butterfly", butterflies_path %>.
    Some of these important and impressive
    habitats and landscape features can be accessed easily from the District&#8217;s towns. Mole Valley District Council
    has produced a
    booklet with a number of walks to enable you to enjoy this landscape and is available from
    <a href="http://www.molevalley.gov.uk/index.cfm?articleid=3594" target="_blank">here</a>.
  </p>

  <p>
    The District is ecologically important due to the presence of many species, habitats and high area of woodland
    cover.
    It is our aim to support the drive to conserve biodiversity for future generations and to highlight the essential
    role
    it
    plays in maintaining our living conditions through providing
    <a href="http://www.ecosystemservices.org.uk/ecoserv.htm" target="_blank">ecosystem services</a>
    such as climate regulation, pollination,
    water purification, genetic resources and flood control.
  </p>

  <p>
    We hope the information here inspires you to explore the landscape, its habitats and identify species and appreciate
    its
    value and beauty. We ask that you respect the countryside by following the
    <a href="http://www.countrysideaccess.gov.uk/things_to_know/countryside_code" target="outside_link">countryside
      code</a>
    and take memories and experiences and leave nothing but footprints.
  </p>

  <p>
    This site has been prepared by, and is maintained by Mole Valley&#8217;s Natural Conservation Group. This group has
    representatives
    from the organisations listed below. The
    <%= link_to "organisations", organisation_list_path %>
    have an interest in Mole Valley&#8217;s natural history and are responsible
    for managing areas of the District&#8217;s rich and varied landscape. Opportunities exist to get involved with these
    organisations
    or the Mole Valley nature conservation groups; if you feel inspired or have a keen interest then please contact them
    directly.
  </p>

  <p>
    <a href="http://www.surreyflora.org.uk/favicon.ico" target="outside_link">Surrey Botanical Society</a><br>
    <a href="http://www.surreycc.gov.uk/sccwebsite/sccwspages.nsf/LookupWebPagesByTITLE_RTF/Lower+Mole+project?open%20document" target="outside_link">
      Lower Mole Countryside Project</a><br>
    <a href="http://www.nationaltrust.org.uk/main/w-global/w-localtoyou/w-south_east/w-south_east-contact_us.htm" target="outside_link">National
      Trust</a><br>
    <a href="http://www.surreywildlifetrust.co.uk/" target="outside_link">Surrey Wildlife Trust</a><br>
    <a href="http://surrey-arg.org.uk/" target="outside_link">Surrey Amphibian and Reptile Group</a><br>
    <a href="http://www.surreybutterflies.org/rss/index.xml" target="outside_link">Butterfly Conservation</a><br>
    <a href="http://www.molevalley.gov.uk/" target="outside_link">Mole Valley District Council</a><br>
    <a href="http://www.rspb.org.uk/groups/dorkinganddistrict" target="outside_link">RSPB Dorking and District Local
      Group</a><br>
    Leatherhead and District Countryside Protection Society<br>
    <a href="http://www.britmycolsoc.org.uk/" target="outside_link">British Mycological Society</a><br>

  </p>
</article>

app/views/pages/whatishere.html.erb
<article>
  <h1>What you can see</h1>
  <%= image_tag "Mute_Swan_heads.jpg", :class => 'main-image', :alt => "Mute Swans" %>
  <p>
    You can find here links to information on a range of characteristic species
    that are found in Mole Valley.
  </p>

  <h2><%= link_to "Birds", birds_path %></h2>

  <h2>Bats</h2>


  <h2><%= link_to "Butterflies", butterflies_path %></h2>

  <p>
    About 60 different kinds of butterfly occur in Britain. More than half of them can be
    seen in Mole Valley, including several nationally scarce butterflies of chalk
    grassland and woodland. The high number of species found locally reflects the location of Mole
    Valley in the warm south east corner of England, and the variety of habitats.
    Fewer species can survive in the north of Britain, although some are moving
    northwards as a result of climate change.
  </p>

  <h2>Dragonflies and Damselflies</h2>

  <h2><%= link_to "Fungi", fungi_path %></h2>

  <h2>Moths</h2>

  <h2><%= link_to "Plants", plants_path %></h2>
</article>